<?php

$LANG_ = array(
 
"english" => array(

	"descriptions" => array(
	
		"button" 		=> "Website Buttons - These are the buttons translations used throughout the website.",
		"title"			=> "Object Titles - These are general translations for object titles.",
		"gallerypage" 	=> "Gallery Page (_gallery.php) Translations",
		"add"			=> "Submission Page (_tpl_add.php) Translations",
		"contact"		=> "Contact Page (_tpl_contact.php) Translations",
		"edit"			=> "Manage Page (_tpl_manage.php) Translations",
		"messages"		=> "Messages Page (_tpl_messages.php) Translations",
		"myaccount"		=> "My Account Page (_tpl_myaccount.php) Translations",
		"callback"		=> "Callback Page (_tpl_callback.php) Translations",
		"head"			=> "Header (_header.php) Translations ",
		"articles"		=> "Article Page (_tpl_articlepage.php / _single.php) Translations ",
		"validate"		=> "Validation - These are general text translations for warning/message alert translations.",
		"date"			=> "Date/ Time Translations",	
		"comment" 		=> "Comment Form Translations",
		"author" 		=> "Author Page (_author) Translations",
		"login" 		=> "Login Page (PPT/framework/ppt_core.php) Translations",
		"ajax" 			=> "Ajax (PPT/ajax/actions.php) Translations",
		"fav" 			=> "Favorites/Wishlist/CompareList Translations",
		"membership" 	=> "Membership Option Translations", 	
				"sp" 	=> "ShopperPress Translations", 
					"cp" =>"CouponPress Translations", 
						"rp" =>"RealtorPress Translations", 
							"ct" =>"ClassifiedsTheme Translations", 
								"object" =>"Objections (Home Page) Translations", 
									"mp" =>"MoviePress Translations", 
										"ap" =>"AuctionPress Translations",
											"rmp" =>"ResumePress Translations",	
												"cmp" =>"ComparisonPress Translations",	
		
	),

	"button" => array(
		
		"1" 			=> "Add",
		"2" 			=> "Edit",
		"3" 			=> "Delete",
		"4" 			=> "View",
		"5" 			=> "Logout",	
		"6" 			=> "Save Changes",
		"7" 			=> "Back",
		"8" 			=> "Cancel",
		"9" 			=> "Reply",
		"10" 			=> "Continue",
		"11" 			=> "Search",
		"12" 			=> "Visit Website",	
		"13" 			=> "More Info",
		"14" 			=> "Contact Owner",		
		"15" 			=> "Share",
		"16" 			=> "Login",
 		"17" 			=> "Set Display Image",
		"18" 			=> "Hide Search Box",
		"19" 			=> "Free",
		"20" 			=> "Free Download",
		"21" 			=> "Pay Now", // checkout button
		"22" 			=> "Invoice", 
		"23" 			=> "Print",
		"24" 			=> "Email A Friend", 
		"25" 			=> "Yes",
		"26" 			=> "No",
		"29" 			=> "Apply Coupon",
		"30" 			=> "Coupon/Discount Code",
		"31" 			=> "Coupon Code Accepted. A %a discount will be applied at checkout.",
		"32" 			=> "Invalid Coupon Code",		
									
	),
	
	"title" => array(
	
		"1" 			=> "Image",
		"2" 			=> "Product",
		"3" 			=> "Actions",
		"4" 			=> "Username",
		"5" 			=> "Expires",
		"6" 			=> "Views",
		"7"				=> "Categories",
		"8"				=> "Category",
		"9"				=> "Stores",
		"10"			=> "Page",
		"11"			=> "Required",
		"12"			=> "Title",
		"13"			=> "Created",
		"14"			=> "Error 404 - Page Not Found",
		"15"			=> "Author Options:",
		"16"			=> "Photos",
		"17"			=> "Description",
		"18"			=> "Short Description",
		"19"			=> "Full Description",
		"20"			=> "Tags/Keywords",
		"21"			=> "Price",
		"22"			=> "Total",	
		"23"			=> "Subtotal",
		"24"			=> "Weight",
		"25"			=> "Shipping",
		"26"			=> "Tax/VAT",
		"27"			=> "Coupon",				
		"28"			=> "Link",
	),
	
	"gallerypage" => array(
	
		"1" 			=> "%a Results Found",		
		"2" 			=> "save this search",		
		"3" 			=> "view saved searches",		
		"4" 			=> "new email alert",		
		"5" 			=> "RSS feed",		
		"6" 			=> "Page %CURRENT_PAGE% of %TOTAL_PAGES%",
		"7" 			=> "<< First",
		"8" 			=> "Last >>",
		"9" 			=> "Switch Display",
		"10"			=> "view as",
		"11"			=> "I'm sorry, we couldn't find any results matching your search criteria.",
				
	),
	
	"add" => array(

		"1" 			=> "Listing Packages / Prices",
		"2" 			=> "Select a package below;",		
		"3" 			=> "FREE",		
		"4" 			=> "%a Day Listing",		
		"5" 			=> "Listing Subscription",	
		"6" 			=> "This is a recurring subscription package, you will be charged every %a unless you cancel your subscription.",		
		"7" 			=> "Listing Length",
		"8" 			=> "This package will last for %a and then the listing will be removed.",		
		"9" 			=> "No Time Limit",		
		"10" 			=> "HTML Descriptions",
		"11" 			=> "Multiple Categories",
		"12" 			=> "File Uploads %a",
		"13" 			=> "Featured Listing",
		"14" 			=> "Google Maps",
		"15" 			=> "File Uploads",
		"16" 			=> "Select Plan",		
		"17" 			=> "Search Description",
		"18" 			=> "Title",
		"19" 			=> "Category",
		"20" 			=> "Tagline",
		"21"			=> "Here you enter a few choice words to grab the users attention.",		
		"22"			=> "Short Description",		
		"23"			=> "The text you enter here will appear on the search results page. Keep is short and descriptive for best results.",		
		"24"			=> "Main Description",		
		"25"			=> "Tags/Keywords",		
		"26"			=> "Keywords help users find your listing when performing searches. Separate each keyword with a comma. e.g. word 1, word 2, word 3",		
		"27"			=> "Additional Details", 
		"28"			=> "Contact Email",
		"29"			=> "Website Address",		
		"30"			=> "Here you enter your website address including the http://",
		"31"			=> "Display Map",
		"32"			=> "Map Location",
		"33"			=> "Enter your address or town/city for the listing location.",				
		"34"			=> "Reciprocal Link Required",		
		"35"			=> "Before your website can be included within our directory you must place a link on your own website back to ours, please tell us where you have placed the link below;",
		"36"			=> "Copy/Paste the code below into your website.",		
		"37"			=> "Then tell us where the code can be found.",		
		"38"			=> "(enter http:// website link)",				
		"39"			=> "Upload Attachments",				
		"40"			=> "Select File",	
		"41"			=> "My Attachments",		
		"42"			=> "Terms and Conditions",
		"43"			=> "I agree to the Terms and Conditions",				
		"44"			=> "Listing Confirmation",				
		"45"			=> "Payment Information",
		"46"			=> "The cost for this listing is",		
		"47"			=> "Listing Process Complete",		
		"48"			=> "Congratulations, your listing has been saved successfully.",		
		"49"			=> "Click here to manage your listings.",				
		"50"			=> "The reciprocal link you provided is invalid.",	
		"51"			=> "Update Successful. New display image set.",		
		"52"			=> "Listing Information",
		"53" 			=> "Upgrade Packages",
		"54" 			=> "Current package:",	
		
		"addnew" 		=> "-- Add New Value --",
		"add1" 			=> "Same Package Price",
		"add2" 			=> "UPLOAD LIMIT REACHED",								
	),	
	
	"contact" => array(
	
		"1" 			=> "Your Name",
		"2" 			=> "Your Email Address",
		"3" 			=> "Your Message",		
		"4" 			=> "Send Message",		
		"5" 			=> "click here to view this post",			
		"6" 			=> "Reported post ID",		
		"7" 			=> "Message Sent Successfully.",
		"8" 			=> "The security code entered was incorrect.",
		"9" 			=> "Contact Listing Owner",		
		"10" 			=> "Complete the form below and we'll send a message to the listing owner on your behalf."		
	),
	
	"edit" => array(
	
		"1" 			=> "Published Listings",
		"2" 			=> "Pending Approval",		
		"3" 			=> "Listed below are all the published listings on your account. Published listings are live and visible on our website.",
		"4" 			=> "The listings below are pending review and are not visible by visitors. Once the listing has been approved it will be visible under the 'published listing' tab.",		
		"5" 			=> "Listing Deleted Successfully",			
		"6" 			=> "Feedback Submitted Successfully.",		
	
	),
	
	"messages" => array(
	
		"1" 			=> "Message",
		"2" 			=> "Messages",
		"3" 			=> "Website Visitor",
		"4" 			=> "This message was sent by a website visitor. To reply you need to contact them directly using the email and/or contact information they provided.",
		"5" 			=> "Send Message",	
		"6" 			=> "Enter the members username above.",
		"7" 			=> "Subject",
		"8" 			=> "Enter a message subject",
		"9" 			=> "Your Message",		
		"10" 			=> "My Messages",
		"11" 			=> "Unread Messages",
		"12" 			=> "Read Messages",
		"13" 			=> "Compose Message",		
 		"14" 			=> "You have reached your daily limit of 15 messages per day.",
 		"15" 			=> "We have no members with that username.",		
		"16" 			=> "Message Deleted Successfully.",
		"17" 			=> "Message Sent Successfully.",		
		"18" 			=> "You have no new messages.",			
		"19" 			=> "You have %a unread messages.",
	),

	"myaccount" => array(
	
		"0" 			=> "Account Options",
		"1" 			=> "My Account", 
		"2" 			=> "My Account Details",
		"3" 			=> "Here you can edit your account details and change your password.",
		"4" 			=> "My Messages",
		"5" 			=> "Here you can read and create messages",
		"6" 			=> "My Coupons",
		"7" 			=> "Here you can view any coupons you've added.",
		"8" 			=> "Add Coupon",
		"9" 			=> "Here you can add a coupon to our website.",		
		"10" 			=> "First Name",
		"11" 			=> "Last Name",
		"12" 			=> "Email",
		"13" 			=> "Website URL",
 		"14" 			=> "A few words about me..",
 		"15" 			=> "Country",		
		"16" 			=> "City",
		"17" 			=> "Address",
		"18" 			=> "Zip/Post Code",
		"19" 			=> "Phone",		
		"20" 			=> "My Photo",
		"21" 			=> "Tick the box to delete your current photo.",
		"22" 			=> "My Details",
		"23" 			=> "Email Alerts",		
		"24" 			=> "My Password",
		"25" 			=> "Enter your new password below.",
		"26" 			=> "Password",
		"27" 			=> "Re-Type Password",			
		"28" 			=> "Email Alert",
		"29" 			=> "Create an email alert by viewing a category and clicking the 'create alert' button. We will email you whenever a new listing is added to a category you setup an alert for.",		
		"30" 			=> "State/Province",
		"31" 			=> "Member Updated Successfully. <br />
		 Please allow a few minutes for account changes to update.",
		"32" 			=> "My Profile Page",		
		"33" 			=> "Company",
		"34" 			=> "VAT Number",		
		"35" 			=> "My Favorites",
		"36" 			=> "Here you can view your favorites and other saved lists.",
		"37" 			=> "My Purchase History",
		"38" 			=> "Here you can view your orders, print of invoices and check an order status.",		
		"39" 			=> "My Compared List",		
		"40" 			=> "This list is empty.",
		"41" 			=> "Select My Photo",
			
		"_paymentstatus0" 		=> "Awaiting Payment",
		"_paymentstatus1" 		=> "Paid & Completed",
		"_paymentstatus2" 		=> "Payment Received",
		"_paymentstatus3" 		=> "Payment Failed",
		"_paymentstatus4" 		=> "Payment Pending",
		"_paymentstatus5" 		=> "Payment Refunded",		
	 
	),
	
	"callback" => array(
	
		"1" 			=> "Payment Complete",
		"2" 			=> "Thank you for your order.",
		"3" 			=> "Your order has now been completed, you will be contacted by our team shortly.",
		"4" 			=> "Payment Pending",
		"5" 			=> "Thank you for your order.",
		"6" 			=> "Your order has now been completed but payment is pending approval, you will be contacted by our team shortly.",
		"7" 			=> "Payment Failed",
		"8" 			=> "Sorry but there was an error during checkout.",
		"9" 			=> "No money has been taken from your account, you will be contacted by our team shortly.",
		"10" 			=> "Transaction Aborted",
		"11" 			=> "No money has been taken.",
		"12" 			=> "No money has been taken from your account, the transaction was not completed successfully.",	
	
	),	

	
	"head" => array(
	
		"1" 		=> "Home",
		"2" 		=> "Enter a keyword..",
		"3" 		=> "Advanced Search",
		"4" 		=> "Logout",
		"5" 		=> "My Account",		
		"6" 		=> "Login",
		"7"			=> "Register",
		"8"			=> "Quick Search",
	
	),
 
 	"articles" => array(
	
		"1" 		=> "Featured Articles",
		"2" 		=> "Latest Articles",			
	),	

	"validate" => array(
		
		"0"			=> "Please complete all fields.",
		"1" 		=> "Please enter your first name.",
		"2" 		=> "Please enter your last name.",
		"3" 		=> "Please enter a valid email address.",
		"4" 		=> "Your passwords do not match. Please check and try again.",
		"5" 		=> "Are you sure you want to do this?",	
		"6" 		=> "What is the sum of %a + %b ?",
		"7" 		=> "Please enter a title for your item.",
		"8" 		=> "Please enter a search description for your item.",
		"9" 		=> "Please enter a few tags/keywords for your item.",			
		"10" 		=> "Only JPG, PNG, GIF, PDF or FLV (video) files are allowed.",
		"11" 		=> "Uploading..",
		"12" 		=> "File type not supported.",
		"13" 		=> "Invalid file",
		"14"		=> "The upload directory is not writ able. Please contact the admin.",	
		"15"		=> "has been added to your list.",		
		"16"		=> "Click Here to view your list.",		
		"17"		=> "is already on your list.",
		"18"		=> "item removed",
		"19"		=> "VAT number has an invalid format.",
		"20"		=> "Please enter a username.",		
		"21"		=> "Please enter a password.",	
		"22"		=> "Please select a package to continue.",								
	),
	
	"date" => array(
	
		"1" 		=> "Day",
		"2" 		=> "Days",
		"second" 				=> "second", 
		"minute" 				=> "minute", 
		"hour" 					=> "hour", 
		"day" 					=> "day", 
		"week" 					=> "week", 
		"month" 				=> "month", 
		"year" 					=> "year", 
		"decade" 				=> "decade",	
			"seconds" 				=> "seconds", 
			"minutes" 				=> "minutes", 
			"hours" 				=> "hours", 
			"days" 					=> "days", 
			"weeks" 				=> "weeks", 
			"months" 				=> "months", 
			"years" 				=> "years", 
			"decades" 				=> "decades",
		
		"bad" => "Bad date",
		"ago" => "ago",
		"expA" 				=> "Expires in %a",
		"expB" 				=> "<strike>Expired %a ago</strike>",
	),
	
	"comment" => array(
	
		"1" 					=> "This post is password protected. Enter the password to view comments.",
		"2" 					=> "Comments are closed.",
		"3" 					=> "You must be logged in to post a comment.",
		"4" 					=> "Name",
		"5" 					=> "Mail (will not be published)",
		"6" 					=> "Website",
		"7" 					=> "Submit Comment",
		"8" 					=> "Leave a Reply",		
		"9" 					=> "No Comments",
		"10" 					=> "1 Comment",		
		"11" 					=> "Comments",	
		
	),

	"author" => array(
	
		"1" 		=> "Send %a a message",
		"2" 		=> "Other listings by %a",
		"3" 		=> "Profile",		
		"4" 		=> "%a last logged in on %b",

	),

	"login" => array(
	
		"1" 		=> "Member Login",
		"2" 		=> "Not yet a member?",
		"3" 		=> "Click here to register a new account.",
		"4" 		=> "Submit",
		"5" 		=> "Forgotten Password?",
		"6" 		=> "Register New Account",
		"7" 		=> "A password will be emailed to you.",
		"8" 		=> "Enter your username or email below;",
		"9" 		=> "Send me a new password",
		"10" 		=> "Username",		
		"11" 		=> "
		<h1>Account Pending</h1><p>Your account is still under review, once approved you will be able to login.</p>",
		"12" 		=> "<h1>Account Suspended</h1><p>We are sorry but your account has been suspended.</p>",
		"13" 		=> "<h1>You're Fired!!</h1><p>We are sorry but your account has been terminated and you are now fired.</p>",		
		"14" 		=> "<strong>ERROR</strong>: You didn't correctly enter the captcha, please try again.",		
		"15" 		=> "Enter your account username or email below and we will send you a new password.",	 	 
		"16" 		=> "Complete the fields below to register a new account. Your login username and password will be sent to the email address you enter below.",			
		"17" 		=> "Please Try Again",
		"18" 		=> "Create Account",		
		"19" 		=> "Select",				
		"20" 		=> "Selected",						
		"_zz1" 					=> "Type the code above:",
		"_zz2" 					=> "A password will be e-mailed to you.",
		"_zz3" 					=> "Username or Email:",
		"_zz4" 					=> "Get New Password",
		"_zz5" 					=> "Please enter your username or e-mail address. You will receive a new password via e-mail.",
		"_zz6" 					=> "Sorry, that key does not appear to be valid.",
		"_zz7" 					=> "You are now logged out.",
		"_zz8" 					=> "User registration is currently not allowed.",
		"_zz9" 					=> "Check your e-mail for the confirmation link.",
		"_zz10" 				=> "Check your e-mail for your new password.",
		"_zz11" 				=> "Registration complete.",
		"reg1" => "Account Login Details",
	
	),	
	
	"ajax" => array(
	
		"1" 					=> "Please login to use this feature.",
		"2" 					=> "Item Deleted Successfully.",
		"3" 					=> "Please login to use this feature.",
		"4" 					=> " <b>New Alert Created.</b> You will be emailed whenever a new listing is added to this category. <br />
		You can manage email alerts under your account details tab.",
		"5" 					=> "Please login to use this feature.",
		"6" 					=> "Search Saved Successfully. Your list has been updated.",		
		"7" 					=> "You don't have any saved search results.",
		"8" 					=> "Item Deleted Successfully. Your list has been updated.",		
		"9" 					=> "No Comments",
		"10" 					=> "1 Comment",		
		"11" 					=> "Comments",		
	),
	
	"fav" => array(
	
		"1"		=> "Add To Wishlist",	
		"2"		=> "Add To Compare",	
		"3"		=> "Add To Favorites",
	),
	
	"membership" => array(
	
		"1"		=> "Access Denied - Please Upgrade",	
		"2"		=> "Access to this page is denied for your membership level. Please upgrade to a different membership to access this page.",	
		"3"		=> "Membership package expires on %a",
		"4"		=> "Payment Required for %a",			
		"5"		=> "Please select a payment option from the list below to make payment for your membership package.",		
		"6"		=> "Does this listing belong to you or your company?",
		"7"		=> "Create an account now and claim this listing.",
		"8"		=> "Claim Listing.",
		"9"		=> "Upgrade Options",
		"10"	=> "Current Membership: %a",
		
		"12"	=> "Submission Limit Exceeded",	
		"13"	=> "You have exceeded the maximum amount of listing available for this membership package.",		
		"14"	=> "Please upgrade to a new membership package to submit new listings.",		
 					
	), 
	

	"object" => array(
			
		"bigsearch1" 			=> "Keyword Search",
		"bigsearch2" 			=> "",
		"bigsearch3" 			=> "Start Search", 		
	
	),

	
	"cp" => array(
	
		"1"		=> "Did it work?",	
		"2"		=> "click to copy &amp; open site",	
		"3"		=> "Success Meter",
		"4"		=> "Related Coupons",	
		"5"		=> "Store",
		"6"		=> "If the coupon belongs to a store, select it here",
		"7"		=> "Click to Reveal",
		"10"		=> "Print Coupon",
		"9"		=> "Click To Visit Website",
		"8"		=> "Code", 	
		
		"11"		=> "Works",
		"12"		=> "Doesn't Work",
		"13"		=> "Search Results",
		"14"		=> "Active",
		"15"		=> "Expired",
		"16"		=> "All",
		"17"		=> "Unknown",
		"18"		=> "Search our coupons, deals and latest offers...",
		"19"		=> "%a coupons and counting!",
		
			
		
		"_tpl_add47" 			=> "Coupon Type",
		"_tpl_add48" 			=> "Coupon Code",
		"_tpl_add49" 			=> "Printable Code",
		"_tpl_add50" 			=> "Offer",
		"_tpl_add51" 			=> "Coupon Code",
		"_tpl_add52" 			=> "enter the coupon code for your promotion",
		"_tpl_add53" 			=> "Start Date",
		"_tpl_add54" 			=> "leave blank if you would like your coupon to start right away",
		"_tpl_add55" 			=> "End Date",
		"_tpl_add56" 			=> "select the date the coupon will expire, leave blank if it doesn't expiry.",	
					
	),
	
), 
);
?>